backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow

media_folder: "public/assets/"
public_folder: "/assets/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
